* day 1
* day 2
* day 3
* day 4
* day 5
* day 6
* day 7
colossus n 巨大的东西
(co/com/con-共同 loss失去 us-n)
(所有丢失的部分聚拢到一起 -> 巨大的东西)

circus n 马戏团
(circ-圆圈 us-n)

legitimacy n 法律性
(leg-法律(legal) itim-n acy-n)
legitim n 法律
delegate v 授权
(de-向下 leg-法律 ate-v)
(把法律权利往下分 -> 授权)

entrenchment n 战壕
(en-使，让  trench n沟(tree树 + bench长椅)  ment-n)
able adj 能够的
enable v 使能
rich adj 富有的
enrich v 使富有

conjure 像魔法变出来一样，突然出现
(con-全部，共同 jur-1.发誓(swear) 2.骂 e)
(絮絮叨叨，念念有词 -> 像魔法变出来一样，突然出现)
conjure up 搭配

injure v 伤害
(in-向内 jure-骂)

squard n 广场
squash v 压碎，碾压
(s qu-拼音去 ash灰)
(灰飞烟灭 -> 压碎，碾压)
(英文单词中q后面固定搭配接的都是u quit/quite/quiet/queue)

* day 8
stabilization n 稳定
(st-待(stay/stand/still) abl(e)-adj ize-v ation-n)
stable adj
stabilize v
stabilization n

residential adj 住宅的
(re-反复 sid-坐(sit) ent-adj/n/v ial-adj)
(日复一日坐在那儿的 -> 住宅的)
resident n 居民

transaction n 交换，交易
(trans-改变 act-做 ion-n)
(通过行动把东西换成别的 -> 交换，交易)
transpot n 交通
transformer n 变形金刚

velocity n 
(cel/vel-速度(拟声) ity-n)

initial adj 最初的
(in-里 it-走 ial-adj)
(走进去的 -> 最初的)
visit v 参观，拜访
(vis-看 it-走)

hike n 增长
(h(igh) (b)ike)
hike in sth 某一方面的增长
The recent hike in train fares comeas a shock to commuters.

limelight n 焦点
(lime-line light)
steal th limelight 抢风头

exemplary adj 优秀的
(example ary-adj)
imaginary adj 想象的，假象的

* day 9
prevailing adj 占优势的，主导的，流行的
(pre-前 vail/val-1.价值 2.力量(古时候力量就是价值) ing-adj)
(强有力的力量推动向前的)
interesting
boring
embarrassing
preview v 预习
predict v 预测 (dict-说)

forsake v 放弃
(for-1.相反 2.因为 sake缘由)
for god sake 看在上帝的份上

example n 例子
(拿出来作为例子)
exemplify v 作为一个..的典型例子
(ex-向外 empl/ampl-拿 ify-v)
exempt v 免除，豁免

deliberate adj 故意的
(de-1.加强 2.否定 3.向下 liber/libr-自由(library图书馆(知识是自由的)) ate-adj/v)
(不自由的，不自然的 -> 故意的，刻意的)
PLA(Chinese People's Liberation Army)

strain n 拉紧
(str-拉伸，延长 (tr)ain)
(拉得很长 -> 拉紧)
street
stream
stress n 压力

* day 10
iffy adj 不合适的，有质疑的
(if如果 f y-adj)
(假如的？ -> 质疑的)

stumble v 1.跌倒 2.说话出错
(st-待(stay) 不连续 -> 口误，跌倒)
humble谦虚(谐音"含苞")
Men trip not on mountains, they stumbles on stones.

vacuous adj 缺乏内容的，无聊的
(vac-空 u-中缀 ous-adj)
vacation n 假期 (空下来的时间)
vacant adj 空的
occupied adj 满的

spectacle n 1.(褒)壮观的景象 2.(贬)可笑的场面
(spect-看 acle-n 看到的场面 -> 1.(褒)壮观的景象 2.(贬)可笑的场面)
respect v 尊重，尊敬
miracle n 奇迹
(mir-虚幻 acle-n)

asymmetry n 不对称
(a-1.加强 2.否定 sym/syn-相同，相等(same) metr-测量(meter米) y-n/adj)
symmetry n 对称

filibuster v 用冗长的话阻碍议员发言
(fil(l)填 i-中缀 bust(er)抓住，逮捕 er-词性贬义，一般为n，这里为v)
(抓住说话的间隙，插满自己的话 -> 用冗长的话阻碍议员发言)

terrorism n 恐怖主义
(terr-恐怖(terriable) or-n ism-n主义)

candidate n 候选人
(cand-白 id-adj ate-adj/n)
(古罗马人竞选时穿白衣)

* day 11
nominate v 提名
(nomin-名字 ate-v/n/adj ate若为v则n形式为ation)
nominee n 被提名者
(ee n表人，跟前面v是被动关系 er n表人，跟前面v是主动关系)
I think you should take yourself seriously but not your work.

thematic
(them(e)主题 at(e)-v/n/adj ic-adj/n)
fanatic adj 狂热的
critic n 批评者

outstrip v 超过
(out外面 str-延长(street stream) ip)
(延长到外面去 -> 超过)
(t/h/e/ip 不决定含义 hip屁股 lip嘴 dip沾)
Ambition will, and should, always outstrip achievement.

nostalgia n 怀旧
(nost-家(nest 巢) alg-疼(all+g拼音割 全割了 -> 疼) ia-n表一种病)
(想到家里以前的事心理很疼 -> 怀旧)
insomnia n 失眠

shatter v 打破，粉碎
(sha-杀 t ter-ger拼个)
(杀它个片甲不留 -> 粉碎)

* day 12
swarm n 特指昆虫的一群
(s-加强 warm温暖)
(聚在一起取暖 -> 一群)

hive n 蜂房
(h(ouse)房子 (l)ive生存)
(生存的房子 -> 蜂房)

nectar n 花蜜
(nect-连接(neck脖子 connect连接) ar-n)
(连接花粉与蜜蜂的东西)
liar
beggar

entomology n 昆虫学
(entom昆虫 ology-n学科)
biology
psychology

invade v 侵略
(in-里 vad-走 e)
(走进去 -> 侵略)
evade v 逃走
(e/ex-向外 vad-走 e)
(走出去 -> 逃走)
* day 13
prominent adj 突出的\\
(pro-向前(普罗米修斯，先知先觉) min-moun山(mountain)/小 ent-adj/n后缀 -> 拔尖的)\\
eminent adj 突出的\\
(e/ex-向外 min-山／小 eng-adj/n后缀 -> 像山一样出来的)\\

evangelical adj 1.福音派教会的 2.狂热的\\
(ev/ex/e-向外 angel-天使 ical-adj后缀 -> 派出天使的)\\

substitute n 替代品\\
(sub-下面 stit-站(stand) ute-n后缀(minute n 小) -> 站在下面候着的东西)\\
eg. There is no substitute for hard work. 没有什么能够替代努力工作。\\

constitution n 宪法\\
(con-全部，共同，所有 stit-站(stand) ution-n后缀 -> 站在所有人立场的东西 -> 宪法)\\

precedent n 先例\\
(pre-向前 ced-走 ent-adj/n后缀(parent par-一对 ent-n后缀) -> 走在前面的事情)\\

intercede v 干涉\\
(inter-在...之间(interview(相互看->)采访 international(国家之间的->)国际的) ced-走 -> 走到中间来)\\

monopoly v 垄断\\
(mono-单(monologue(独自说话->)独白) poly-用(employ雇佣) -> 只用一家)\\

* day 14
conniption n 歇斯底里\\
(con-全部 nip-不(nope 元音主要发音，辅音辅助表义) tion-n后缀 -> 全部都否定)\\

frothy adj 起泡的\\
(froth n 泡沫(fr->fire o->泡 th->嘶嘶声 -> 用火煮开后，锅里都气泡) y-adj后缀)\\

distortion n 曲解
(dis-否定 tort-扭曲，扭转(turn) ion-n后缀 -> 向不好的方向转)

torture v 折磨
(tort-扭曲 ure-n后缀 -> 让人非常拧巴)

volatile adj 不稳定的
(vol-转动(拟声) at(e)-n/v/adj后缀 ile-adj后缀 -> 一直转个不停的)

avert v 避免
(a-加强(ad)/否定(ab) vert-转动(拟声) -> 转开了，没打到)

* day 15
successor n 继任者
(suc/sub-向下(subway地铁) cess-走 or-n后缀，表人 -> 继续往下走下去的人)

recession n 经济衰退
(re-返回 cess-走 ion-n后缀 -> 往回走)

success v 成功
(suc-向下 cess-走 -> 可以继续往下走下去了)

rein n 缰绳
(re-往回 in-向内 -> 把缰绳往里，往回拉)

acquire v 获得
(ac-加强 quir/quis-获得(require 往回拿->需求))
acquisition n 并购
(ac-加强 quir/quis-获得(require 往回拿->需求) ition-n后缀)

squander v 浪费
(s->死 quan->哐，钱币声 der->流水声 -> 花钱如流水)

dominant adj 主导的
(dom/domin-家(domestic国内的) ant-/n/adj后缀(account n important adj) -> 家的地位永远都是主导的)

* day 16
  solitary adj 单独的，孤独的
  (sol-单独(solo独奏 audio以o结尾常跟声音有关) it-走 ary-adj后缀)
  (一个人走的 -> 单独的，孤独的)
  
  solitude n 孤独
  (sol-单独 itude-n后缀，表抽象)

  crucial adj 关键的
  (cruc-十字，交叉(cross) ial-adj后缀)
  
  distinction n 区别
  (dis-发散 (s)tinct-刺(sting叮，刺) ion-n后缀)

  malicious adj 恶意的
  (mal-坏(male男) ic(e)-n后缀(novice新手 nov-新(new)) ous-adj后缀)
  (bene-好(benefit))

  simultaneous adj 同时的
  (sim-相同(same) ul-中缀 tane-时间(time) ous-adj后缀)
  (相同时间的 ->v 同时的)

  revenge n 复仇
  (re-往回 venge-惩罚(谐音联想“敢玩哥”))
  (反回来惩罚 -> 复仇)

  vengeful adj 复仇心重的
  (venge-惩罚 ful-adj后缀，表满)

* day 17
  autonomous adj 自主的
  (auto-自动 nom-名字，权利(name) ous-adj后缀)
  (自己有权利的 -> 自主的)
  
  nomination n 提名
  (nom-名字 in-向里 ation-n后缀)
  (名字上榜了 -> 提名)

  radical adj 彻底的，激进的
  (rad-根 ic-adj/n后缀 al-adj/n后缀)
  (根除了的 -> 彻底的，激进的)
  (ic-adj后缀 fanatic 狂热的)
  (ic-n后缀 critic 批评家)
  (al-adj后缀 personal 个人的)
  (al-n后缀 animal 动物)

  compulsory adj 强制的，必须的
  (com-全部，共同，所有 puls-推(pull + push) ory-adj/n后缀)
  (推拉着全部参加的 -> 强制的，必须的)
  (ory-n后缀 factory(fact-做) 做东西的地方->工厂)
  (ory-n后缀 victory(vict-胜利) 胜利)
  (ory-adj后缀 satisfactory 满意的)
  
  concur v 认为
  (con-全部，共同，所有 cur-跑，流动(car))
  (全都跑向一个地方，想法一致 -> 认为)
  
  currency n 货币
  (cur-跑，流通，流动(car) r ency-n后缀)
  (在市场上能流通的东西 -> 货币)
  
  liability n 责任
  (li(e)-存在 ability-n后缀，表能力)
  (每个人都要存在的东西 -> 责任)
* day 18
  duration n 持续时间
  (dur-持续(durex dur-持久 ex-极限 杜蕾斯) ation-n后缀)
  Love can not be measured by its duration.
  durable adj 持久的

  pinch n 疼痛
  (pin n 大头针 ch-ouch啊呦)
  
  retain v 保持
  (re-1.反复 2.返回 tain-拿(take in) 反复不断的拿 -> 保持)
  
  detain v 扣留
  (de-向下 tain-拿 拿下 -> 扣留)
  
  tuition n 学费
  (tuit/tut-教 ion-n后缀)
  tutor n 家庭教师
  intuition n 直觉
  (in-不 tuit/tut-教 ion-n后缀 不用教的东西 -> 直觉)
  
  beer n 啤酒
  peer n 同龄人
  (同龄人在一起喝啤酒)
* day 19
  consistency n 连贯性
  (con-全部，共同，所有 sist-站立(stand) ency-n后缀)
  (全部站在一起，紧密排在一起 -> 连贯性)
  
  resist v 抵抗
  (re-1.返回，相反 2.重复 sist-站立 站在相反的位置 -> 抵抗)

  freakish adj 畸形的
  ()

  horn n 角
  corn n 玉米
  porn n 黄色，成人
  scorn 鄙视，轻蔑
  (sc s-死 c-cry喊 死命喊，看不起 -> 鄙视)
  ( 美 [skɔ:rn] k->g s后面加辅音，辅音要发浊辅音 (student t->d))

  fudge v 篡改
  (fu-服 d-的 ge-哥 服了哥，你老是篡改数据 -> 篡改)
  
  zigzag n z字形状
  (zig/zag-急转弯 2哥急转弯 -> z字形状)
  
  volume n 卷
  (vol-转动(拟声) ume-n后缀)
  volatility n 挥发性
  (vol-转动(拟声) at(e)-n/v/adj后缀 + il(e)-adj后缀 ity-n后缀)
  (转着圈的挥发没了)
  
  fertile adj 土壤肥沃的，生育能力强的
  (fert- ile-adj后缀)
* day 20  
  barbarian n 野蛮人 adj 野蛮的，未开化的
  (barbar-胡说(拟声，小孩说话的原始阶段) adj/n后缀)
  (ian-adj后缀 Canadian adj 加拿大的)
  (ian-n后缀，表人 historian n 历史学家 comedian n 喜剧演员)
  
  prosper v 使繁荣，使成功 
  (pro-向前 sper-希望 向前是能看到希望的)
  (美 [ˈprɑ:spə(r)] p->b)
  prosperous adj 繁荣的
  prosperity n 希望
  desperate adj 绝望的
  (de-1.向下 2.否定 3.加强 sper-希望 ate-v后缀)
  (没有希望的 -> 绝望的)
  
  stumble v 跌倒，出错
  (st-脚(stay, stand, still) ble -> 跌倒，出错)
  humble adj 谦虚的
  (hum-泥土 ble 接地气的 -> 谦虚的)
  
  equivalent adj 对等的
  (equ-相等 i-中缀 val-1.价值(value) 2.强壮 ent-adj后缀(present adj 现在的))
  (价值相等的 -> 对等的)
  valid adj 有效的
  (id-adj后缀 stupid adj 愚蠢的)
  invalid adj 无效的
  
  lavish adj 浪费的
  (lav-冲洗 ish-adj (childish adj 幼稚的))
  (花钱像冲洗的 -> 浪费的)
  lavatory n 盥洗室
  (冲水的地方 -> 盥洗室)
* day 21
combustible adj 易燃的
(com-全部，共同，所有 bust-燃烧(burn) ible-adj后缀，表能)
(所有东西都能燃烧的 -> 易燃的)
combustion n 燃烧，烧毁

disdain v 鄙视
(dis-1.否定 2.发散 dain-尊严(联想“大人”))
(没有尊严，看不起 -> 鄙视)

audacious adj 大胆的
(aud-bold adj 大胆的 n 粗体字 acious-adj后缀，表多的)
(acious-adj后缀，表多的 space n 空间 spacious adj 空间很大的)
(acious-adj后缀，表多的 rap n/v 强奸，掠夺 rapacious adj 贪婪的)

exude v 渗出，流出
(ex-向外 ude)
include v 包含

sustain v 维持
(sus-向下 tain-拿(take in) 拿着走下去，不丢弃 -> 维持)
detain v 拘留
(de-向下 tain-拿(take in) 拿下 -> 拘留)
